### ISSUE TITLE
.edit command not working with "emacsclient -t"

### ISSUE THREAD

**Issue by vapniks** [awslabs/aws-shell#104]
.edit command works when I have EDITOR set to nano, but not when it's set to "emacsclient -t".
I get the following error in that case:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws-shell", line 9, in <module>
    load_entry_point('aws-shell==0.1.0', 'console_scripts', 'aws-shell')()
  File "/usr/local/lib/python2.7/dist-packages/awsshell/__init__.py", line 70, in main
    shell.run()
  File "/usr/local/lib/python2.7/dist-packages/awsshell/app.py", line 287, in run
    result = self._dot_cmd.handle_cmd(text, application=self)
  File "/usr/local/lib/python2.7/dist-packages/awsshell/app.py", line 175, in handle_cmd
    return self.HANDLER_CLASSES[cmd_name]().run(parts, application)
  File "/usr/local/lib/python2.7/dist-packages/awsshell/app.py", line 100, in run
    p = self._popen_cls([editor, f.name])
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jamesls** [comment]
Confirmed the issue.  Thanks for reporting.
