### ISSUE TITLE
Version 0.10 has a bug

### ISSUE THREAD

**Issue by fatelei** [awslabs/aws-shell#122]
```
First run, creating autocomplete index...

Traceback (most recent call last):
  File "/Users/wanglei/.virtualenvs/pyenv/bin/aws-shell", line 11, in <module>
    sys.exit(main())
  File "/Users/wanglei/.virtualenvs/pyenv/lib/python2.7/site-packages/awsshell/__init__.py", line 47, in main
    write_index(index_file)
  File "/Users/wanglei/.virtualenvs/pyenv/lib/python2.7/site-packages/awsshell/makeindex.py", line 63, in write_index
    index_command(current, help_command)
  File "/Users/wanglei/.virtualenvs/pyenv/lib/python2.7/site-packages/awsshell/makeindex.py", line 55, in index_command
    index_command(child, sub_help_command)
  File "/Users/wanglei/.virtualenvs/pyenv/lib/python2.7/site-packages/awsshell/makeindex.py", line 55, in index_command
    index_command(child, sub_help_command)
  File "/Users/wanglei/.virtualenvs/pyenv/lib/python2.7/site-packages/awsshell/makeindex.py", line 43, in index_command
    arg, arg_obj.argument_model)
TypeError: generate_shorthand_example() takes exactly 4 arguments (3 given)
```

I check the code, and find this bug has been fixed. But the package in pypy is still not working. Please release a new version.

**Comment by jonoirwinrsa** [comment]
In case it helps anyone.. To fix this issue I did the following:

**Installed the correct versions of rsa and colorama:**
sudo pip install 'rsa<=3.3.0,>=3.1.2'
sudo pip install 'colorama<=0.3.3,>=0.2.5'

**then removed aws-shell and reinstalled:**
sudo pip uninstall aws-shell
sudo pip install aws-shell

**And finally it ran with:**
aws-shell

**Comment by jamesls** [comment]
Version 0.1.1 is now available: https://pypi.python.org/pypi/aws-shell/0.1.1

You should be able to just run `pip install --upgrade aws-shell` (or `sudo pip install --upgrade aws-shell` depending on how you have python set up) to pull in the latest changes.

Let me know if that doesn't work for you and I'll reopen and take another look.

**Comment by fatelei** [comment]
@jamesls It works, thanks a lot.
