### ISSUE TITLE
Does not run on python 3.5

### ISSUE THREAD

**Issue by aavileli** [awslabs/aws-shell#153]
[Demon]$aws-shell

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (s3transfer 0.0.1 (/usr/lib/python3.5/site-packages), Requirement.parse('s3transfer<0.2.0,>=0.1.0'), {'boto3'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aws-shell", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2989, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 675, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 's3transfer<0.2.0,>=0.1.0' distribution was not found and is required by boto3

**Comment by donnemartin** [comment]
Hi @aavileli, I'm not seeing this issue on a fresh virtualenv with Python 3.5.

From your traceback, it seems like there might be an issue with the `s3transfer` dependency installed on your system.  Does running the following fix it?

     $ pip install s3transfer --upgrade

If not, what's your output of:

     $ pip freeze

**Comment by aavileli** [comment]
python --version
Python 3.5.2

pip freeze 
ansible==2.1.0.0
appdirs==1.4.0
awscli==1.10.51
awslogs==0.5.0
Beaker==1.8.0
beautifulsoup4==4.5.1
boto3==1.4.0
botocore==1.4.53
Brlapi==0.6.5
cffi==1.7.0
chardet==2.3.0
colorama==0.3.7
configobj==5.0.6
cryptography==1.4
cupshelpers==1.0
Cython==0.24.1
docutils==0.12
eventlet==0.19.0
greenlet==0.4.10
idna==2.1
Jinja2==2.8
jmespath==0.9.0
louis==3.0.0
lxml==3.6.4
Mako==1.0.4
MarkupSafe==0.23
mock==2.0.0
packaging==16.7
paramiko==2.0.2
pbr==1.10.0
prompt-toolkit==1.0.7
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
Pygments==2.1.3
pygobject==3.20.1
pyparsing==2.1.8
python-dateutil==2.5.3
pyxdg==0.25
PyYAML==3.11
requests==2.11.1
rsa==3.4.2
s3transfer==0.1.3
six==1.10.0
team==1.0
termcolor==1.1.0
urllib3==1.17
virtualenv==15.0.3
wcwidth==0.1.7

**Comment by aavileli** [comment]
I have got it working now Uninstalled the following 
botocore awscli and then installed using the following options 
pip install aws-shell --no-cache-dir
