### ISSUE TITLE
Installation error with brew/macosx

### ISSUE THREAD

**Issue by r0fls** [awslabs/aws-shell#177]
After running `brew install aws-shell` I get the following error when trying to run `aws-shell`:

```
$ aws-shell
Traceback (most recent call last):                                                                              
  File "/usr/local/Cellar/aws-shell/0.1.1/libexec/bin/aws-shell", line 5, in <module>
    from pkg_resources import load_entry_point                                                    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside                                                                                                
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)                                                                      
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()                                                                    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)                                                   
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())                                         
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)                  
pkg_resources.ContextualVersionConflict: (botocore 1.5.58 (/Library/Python/2.7/site-packages/botocore-1.5.58-py2.7.egg), Requirement.parse('botocore==1.4.50'), set(['awscli']))
```

**Comment by joguSD** [comment]
Hm seems that there's a version conflict between `botocore` installed on your system python and the version that the `aws-shell` is expecting. How are you managing python packages on your machine?

**Comment by r0fls** [comment]
I'm simply managing my python packages with pip.

**Comment by joguSD** [comment]
Yeah my guess would be some kind of configuration conflict between the packages provided by pip and brew. Can you try removing the brew package and installing the shell via pip? Or is there a specific reason you chose to use brew?

**Comment by r0fls** [comment]
I just chose brew because it seemed easiest. I'm sure I can find a workaround. Removing it with brew and installing with pip results in:

>error: botocore 1.5.74 is installed but botocore==1.5.92 is required by set(['awscli'])

However I'm sure I can find a solution to this myself, thanks.
