### ISSUE TITLE
ImportError: No module named filters

### ISSUE THREAD

**Issue by haggistech** [awslabs/aws-shell#188]
Getting this error with a fresh install of aws-shell

awscli is already installed

**Comment by joguSD** [comment]
Can you post the full traceback?

**Comment by haggistech** [comment]
Sorry for Delay

```
Traceback (most recent call last):
  File "/usr/local/bin/aws-shell", line 7, in <module>
    from awsshell import main
  File "/usr/local/lib/python2.7/dist-packages/awsshell/__init__.py", line 7, in <module>
    from awsshell import shellcomplete
  File "/usr/local/lib/python2.7/dist-packages/awsshell/shellcomplete.py", line 16, in <module>
    from prompt_toolkit.completion import Completer, Completion
  File "/home/haggis/.local/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/haggis/.local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/haggis/.local/lib/python2.7/site-packages/prompt_toolkit/application.py", line 3, in <module>
    from .buffer import Buffer, AcceptAction
  File "/home/haggis/.local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 7, in <module>
    from .auto_suggest import AutoSuggest
  File "/home/haggis/.local/lib/python2.7/site-packages/prompt_toolkit/auto_suggest.py", line 13, in <module>
    from .filters import to_cli_filter
ImportError: No module named filters
```

**Comment by joguSD** [comment]
This seems like an issue with prompt_toolkit. What is the out of `pip freeze`?

With a clean virtualenv I did:
`pip install aws-shell`
and got the following for `pip freeze`:
```
aws-shell==0.2.0
awscli==1.12.2
boto3==1.4.8
botocore==1.8.2
colorama==0.3.7
configobj==5.0.6
docutils==0.14
jmespath==0.9.3
prompt-toolkit==1.0.15
pyasn1==0.4.2
Pygments==2.2.0
python-dateutil==2.6.1
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.11
six==1.11.0
wcwidth==0.1.7

```

**Comment by haggistech** [comment]
aws-shell==0.2.0
awscli==1.13.0
boto3==1.4.7
botocore==1.8.3
colorama==0.3.7
configobj==5.0.6
docutils==0.14
futures==3.1.1
jmespath==0.9.3
prompt-toolkit==1.0.15
pyasn1==0.1.9
Pygments==2.2.0
python-dateutil==2.6.1
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.11
six==1.10.0
wcwidth==0.1.7

Same issue, i will redo and try again

**Comment by joguSD** [comment]
Were you ever able to get the shell working? It might be worth a try to use: `pip install aws-shell --force-reinstall`. If that doesn't work I'd be suspicious of how your python/environment are setup. It may be a discrepancy between where python packages are located. I noticed the shell is installed to: `/usr/local/lib/python2.7/dist-packages/` while `prompt-toolkit` is installed to `/home/haggis/.local/lib/python2.7/`. Have you installed the `aws-shell` via your OS package manager?

**Comment by joguSD** [comment]
Closing due to inactivity.
