### ISSUE TITLE
 No such file or directory error

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-shell#230]
I updated my aws-shell and when I open it, it says its the first run of this version, so it will build the docs in the background. Then after a while I get an exception:

> 
> Traceback (most recent call last):
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awsshell\makeindex.py", line 88, in write_doc_index
>     do_write_doc_index(db, help_command, close_db_on_finish=should_close)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awsshell\makeindex.py", line 93, in do_write_doc_index
>     _index_docs(db, help_command)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awsshell\makeindex.py", line 111, in _index_docs
>     _index_docs(db, sub_help_command)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awsshell\makeindex.py", line 108, in _index_docs
>     text_docs = render_docs_for_cmd(sub_help_command)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awsshell\makeindex.py", line 117, in render_docs_for_cmd Emacs  [F4] Single Column  [F5] Help: ON  [F9] Focus: cli  [F10] Exit
>     help_command(None, None)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awscli\customizations\commands.py", line 358, in __call__
>     docevents.generate_events(self.session, self)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\botocore\docs\bcdoc\docevents.py", line 46, in generate_events
>     help_command=help_command)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\botocore\session.py", line 672, in emit
>     return self._events.emit(event_name, **kwargs)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\botocore\hooks.py", line 356, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\botocore\hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\botocore\hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awscli\customizations\commands.py", line 376, in doc_synopsis_start
>     if not help_command.synopsis:
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awscli\customizations\commands.py", line 326, in synopsis
>     return self._get_doc_contents('_synopsis')
>   File "c:\users\my user\appdata\local\programs\python\python36\lib\site-packages\awscli\customizations\commands.py", line 347, in _get_doc_contents
>     with _open(doc_path) as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\my user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\awscli\\examples\\emr\\create-cluster-synopsis.txt'

**Comment by CloudZero458** [comment]
I'm having the exact same problem

**Comment by feinstein** [comment]
I added a blank file with the same name at that folder and the error disappeared, probably that specific documentation will not be fetch, but at least it works for the rest.

**Comment by LesterCovax** [comment]
@feinstein you should be able to pull the content from here: 
https://raw.githubusercontent.com/aws/aws-cli/develop/awscli/examples/emr/create-cluster-synopsis.txt

**Comment by feinstein** [comment]
Thanks
