### ISSUE TITLE
aws-shell is not working in Amazon Linux 2 after installing

### ISSUE THREAD

**Issue by leotoras** [awslabs/aws-shell#240]
Hi, Im getting the following error after installing aws-shell in my EC2 Amazon Linux 2:

[ec2-user@tmp]$ aws-shell
First run, creating autocomplete index...
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/aws-shell", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awsshell/__init__.py", line 47, in main
    write_index(index_file)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/awsshell/makeindex.py", line 69, in write_index
    result = json.dumps(index)
  File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
MemoryError

Are you able to help ?

**Comment by claudioabudio** [comment]
Same here I also tried it by installing it using pip install aws-shell and got the same error message

**Comment by claudioabudio** [comment]
Actually not sure what exactly fixed it, however i have done the following on the ec2 instance: 
pip3 install awscli
pip3 install awsshell

Then ran aws-shell and worked fine.

So maybe it needs to run with python3 now, but I am not sure :)
