### ISSUE TITLE
'amplify init' error: UnrecognizedClientException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by ns-github14** [awslabs/aws-shell#248]
init failed
UnrecognizedClientException: The security token included in the request is invalid.
    at Object.extractError (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.extractError (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\rest_json.js:55:8)
    at Request.callListeners (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\neelanshi sharma\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:690:12) {
  code: 'UnrecognizedClientException',
  time: 2020-09-29T10:25:46.488Z,
  requestId: '18798b13-d920-4c5a-be71-7c8ab8baa6a1',
  statusCode: 403,
  retryable: false,
  retryDelay: 36.07608709751893
}

**Comment by Ravivarma144** [comment]
**i am also getting same issue please help** 

AccessDeniedException: User: arn:aws:iam::482703356810:user/nimbletextract is not authorized to perform: amplify:CreateApp on resource: arn:aws:amplify:eu-west-2:482703356810:apps/*
    at Object.extractError (C:\Users\Geeta konchada\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)

**Comment by mubeenaTechknocks** [comment]
i have same error 

init failed
UnrecognizedClientException: The security token included in the request is invalid.
    at Object.extractError (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.extractError (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\rest_json.js:55:8)
    at Request.callListeners (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:690:12) {
  code: 'UnrecognizedClientException',
  time: 2020-12-24T07:09:21.295Z,
  requestId: 'a9acfa0c-2d09-458b-8e48-58bdc8eadd47',
  statusCode: 403,
  retryable: false,
  retryDelay: 55.35405568410234
}

**Comment by ns-github14** [comment]
.

**Comment by GMerakis** [comment]
was there a solution?
The guide/tutorial as of today has no mention of this whatsoever

**Comment by WalterWoshid** [comment]
BUMP
