### ISSUE TITLE
Error on first run while createing autocomplete index

### ISSUE THREAD

**Issue by sebastiaopf** [awslabs/aws-shell#260]
Fresh install on Linux Mint, upgraded awscli and botocore packages.

Running for the first time returns an error while creating the autocomplete index as shown below:

```bash
$ aws-shell
First run, creating autocomplete index...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/awsshell/utils.py", line 84, in file_contents
    with open(filename, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/**my-user-name-removed**/.aws/shell/cache/completions-1.19.62.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/awsshell/index/completion.py", line 63, in load_index
    contents = self._fslayer.file_contents(filename)
  File "/usr/local/lib/python3.6/dist-packages/awsshell/utils.py", line 87, in file_contents
    raise FileReadError(str(e))
awsshell.utils.FileReadError: [Errno 2] No such file or directory: '/home/**my-user-name-removed**/.aws/shell/cache/completions-1.19.62.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/awsshell/__init__.py", line 39, in main
    index_str = indexer.load_index(utils.AWSCLI_VERSION)
  File "/usr/local/lib/python3.6/dist-packages/awsshell/index/completion.py", line 65, in load_index
    raise IndexLoadError(str(e))
awsshell.index.completion.IndexLoadError: [Errno 2] No such file or directory: '/home/**my-user-name-removed**/.aws/shell/cache/completions-1.19.62.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/model.py", line 302, in operation_model
    model = self._service_description['operations'][operation_name]
KeyError: 'ExecuteCommand'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aws-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/awsshell/__init__.py", line 47, in main
    write_index(index_file)
  File "/usr/local/lib/python3.6/dist-packages/awsshell/makeindex.py", line 70, in write_index
    index_command(current, help_command)
  File "/usr/local/lib/python3.6/dist-packages/awsshell/makeindex.py", line 61, in index_command
    sub_help_command = sub_command.create_help_command()
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 390, in create_help_command
    command_table = self._get_command_table()
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 341, in _get_command_table
    self._command_table = self._create_command_table()
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 380, in _create_command_table
    command_object=self)
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/session.py", line 677, in emit
    return self._events.emit(event_name, **kwargs)
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/ecs/__init__.py", line 37, in inject_commands
    .operation_model('ExecuteCommand'),
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/utils.py", line 1148, in _cache_guard
    result = func(self, *args, **kwargs)
  File "/home/**my-user-name-removed**/.local/lib/python3.6/site-packages/botocore/model.py", line 304, in operation_model
    raise OperationNotFoundError(operation_name)
botocore.model.OperationNotFoundError: ExecuteCommand
```

I can run additional tests or collect more data if needed.

**Comment by s1mrankaur** [comment]
Same issue! I am on Windows. Is there a solution?
